### ISSUE TITLE
참가비와 자격(?????)에 대해 질문드려요!

### ISSUE THREAD

**Issue by jarvistouchworks** [sprintseoul/general#1]
참가비가 있을까요?
그리고 참가 자격... 이라고 해야하나? 그런게 있을까요?
오픈소스 프로젝트에 참여한 적도 없고, 뭔가 이슈를 해결할 수준도 안된다고 생각을 하고있는데 기여는 하고싶고 그런 상태라...

**Comment by lqez** [comment]
문의주셔서 감사합니다.
참가 자격은 오픈소스 커뮤니티에 감사하는 마음과 프로젝트에 기여하고자 하는 의지면 충분할 것 같습니다.

처음 참가하는 분들을 위해 짧은 문서를 준비해보았습니다.
https://github.com/sprintseoul/general/wiki/for-sprint-beginners

참가비는 없고, 당일 상황에 따라 점심이 제공될 수도 있고 안될 수도 있습니다.

부담 갖지 마시고 참석해주세요.
감사합니다.
