### ISSUE TITLE
이슈 목록을 어디서 확인할 수 있나요? (처음 참가합니다)

### ISSUE THREAD

**Issue by taehwanyoon** [sprintseoul/general#2]
페이지들을 살펴 보았는데, 안내에 beginner 에 맞는 이슈를 찾아보라고 되어 있는데 이슈 목록이 어디 있는지 잘 못찾겠습니다. (죄송합니다. 초보자라서..)
알려주시면 감사하겠습니다.

**Comment by lqez** [comment]
대부분 GitHub에 프로젝트가 위치해 있는데, 각 프로젝트의 `Issues`에 이슈들이 등록되어 있습니다. (지금 질문을 등록해주신 이 곳과 같습니다)
예: Pandas 이슈 중, `good first issue` 라벨로 필터링
https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Django와 같이 GitHub의 Issues 기능을 사용하지 않고 별도의 이슈 트래커를 사용하는 경우도 있습니다.
예: https://code.djangoproject.com/query

감사합니다.
