### ISSUE TITLE
이미 완료한 양식을 수정할 수는 없나요?

### ISSUE THREAD

**Issue by riemannulus** [sprintseoul/general#3]
`어떤 프로젝트에 기여하고 싶으신가요?` 파트에서 원하는 프로젝트를 하나 체크하지 못한 채 양식 보내기를 했습니다. 수정하고 싶은데 가능한가요?

**Comment by lqez** [comment]
폼을 접수한 후 수정할 수 있도록 변경하였습니다. 해당 폼에서 지정한 프로젝트 외에도 현장에서 소개를 듣고 원하는 프로젝트를 자유롭게 스프린트하실 수 있습니다. 설문 결과는 수요 조사로만 사용하고 있으니 별도로 수정하실 필요는 없을 것 같습니다.

감사합니다.
