### ISSUE TITLE
다음 일정은 언제 인지 알 수 있을까요?

### ISSUE THREAD

**Issue by dimsssss** [sprintseoul/general#4]
참여하고 싶은데 다음 일정이 언제인지 궁금합니다. 비 정기적으로 하는 활동인가요?

**Comment by lqez** [comment]
@dimsssss님 안녕하세요, 스프린트서울은 2018년 12월부터 격월로, 짝수 월에 스프린트를 진행하고 있습니다.
8월달에는 [파이콘 한국 2019의 스프린트 행사](https://www.pycon.kr/program/sprint)에 참가차 별도의 스프린트는 진행하지 않습니다.

다음 스프린트서울은 2019년 10월에 있을 예정이며, 행사 정보는 https://www.sprintseoul.org/ 에 공지됩니다.

감사합니다.
