### ISSUE TITLE
안녕하세요. 취소 관련 문의 남깁니다.

### ISSUE THREAD

**Issue by young-tech** [sprintseoul/general#5]
안녕하세요. 12월 스프린트를 신청한 학생입니다. 그런데 제가 못가게 될 사정이 생겼습니다. 신청취소릃 할 수있을까요?

**Comment by lqez** [comment]
ez@zerobased.co로 신청하신 이메일주소를 포함해 메일을 보내주시면 취소 처리해드리겠습니다. 감사합니다.
