### ISSUE TITLE
7월 행사는 언제 하나요?

### ISSUE THREAD

**Issue by roseline124** [sprintseoul/general#6]
언제쯤 시작할까요?

**Comment by lqez** [comment]
지난 2월, 5월 스프린트 모임의 진행이 원할하지 않았던 관계로 진행이 미뤄지고 있습니다.
변동 사항이 있을시, 다시 알려드리겠습니다.

감사합니다.

**Comment by roseline124** [comment]
네 알겠습니다 :)
감사합니다

**Comment by lqez** [comment]
2022년 1월 22일, 온라인으로 다시 시작해봅니다.
https://sprintseoul.org/2022-01-22/

**Comment by roseline124** [comment]
너무 기뻐요!! 꼭 참가합니당
